" We have a dark background
set bg=dark
"colorscheme molokai
hi Normal ctermbg=none
"set colorcolumn=81
set cursorline
set pastetoggle=<F2>

" CTRL+PageUp & CTRL+PageDown to switch between tabs, also tn for tab forward
" and th for tab backwards
map <C-PageUp> :tabprevious<CR>
map <C-PageDown> :tabnext<CR>
map th :tabp<CR>
map tn :tabn<CR>

" In comand mode, use tab to switch to next window (MC style)
map <Tab> <C-W>w
map <S-Tab> <C-W>W

map <F12> :tabnew<CR>

"make < > shifts keep selection
vnoremap < <gv
vnoremap > >gv

" Tab things here
set expandtab
set ts=2
set sw=2
set sts=2

set pastetoggle=<F10>

" print linenumbers
set number

"function! NumberToggle()
"  if(&relativenumber == 1)
"    set number
"  else
"    set relativenumber
"  endif
"endfunc
"nnoremap <C-n> :call NumberToggle()<cr>
"
"Set CTRL+n to toggle between numbers and relative linenumbers
nnoremap <C-n> :set rnu!<cr>
nnoremap <C-l> :set nu!<cr>

" Be able to scroll through the file
"set mouse=a

"map <xCSI>[62~ <MouseDown>


 set nocompatible               " be iMproved
 filetype off                   " required!

 set rtp+=~/.vim/bundle/Vundle.vim
 call vundle#begin()

 " let Vundle manage Vundle
 " required! 
 Plugin 'VundleVim/Vundle.vim'

 nmap <F8> :TagbarToggle<CR>
 nmap <F4> :NERDTreeToggle<CR>

 " My Plugins here:
 "
 " original repos on github
 Plugin 'tpope/vim-fugitive'
 Plugin 'Lokaltog/vim-easymotion'
 Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
 Plugin 'tpope/vim-rails.git'
 Plugin 'vim-airline/vim-airline'
 Plugin 'vim-airline/vim-airline-themes'
 Plugin 'kien/ctrlp.vim'
 Plugin 'scrooloose/nerdtree'
 Plugin 'eagletmt/neco-ghc'
 Plugin 'pearofducks/ansible-vim'
" Plugin 'Valloric/YouCompleteMe'
 Plugin 'c.vim'
 Plugin 'rodjek/vim-puppet'
 Plugin 'lepture/vim-jinja'
 Plugin 'chr4/nginx.vim'
 " vim-scripts repos
 Plugin 'L9'
" Plugin 'FuzzyFinder'
 Plugin 'Tagbar'
 " non github repos
 Plugin 'wincent/command-t'
 " git repos on your local machine (ie. when working on your own plugin)
 " Bundle 'file:///Users/gmarik/path/to/plugin'
 " ...
call vundle#end()
 filetype plugin indent on     " required!
 "
 " Brief help
 " :BundleList          - list configured bundles
 " :BundleInstall(!)    - install(update) bundles
 " :BundleSearch(!) foo - search(or refresh cache first) for foo
 " :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
 "
 " see :h vundle for more details or wiki for FAQ
 " NOTE: comments after Bundle command are not allowed..
let g:airline_powerline_fonts=1
set laststatus=2
let g:airline#extensions#tabline#enabled = 1
"let g:airline_theme = 'kalisi'
let g:airline_theme = 'molokai'
"let g:airline_theme = 'base16-spacemacs'
"let g:airline#extensions#tabline#left_sep='<'
"let g:airline#extensions#tabline#left_alt_sep='|'
"let g:airline#extensions#tabline#right_sep='>'
